### ISSUE TITLE
capwap-wtp 1.2.1 crashes after some time

### ISSUE THREAD

**Issue by nm-mrt** [travelping/smartcapwap#8]
Hi, 

capwap starts up. In the beginning there is no internet connection which explains the "Could not resolve" messages. 
[capwap-crash.log.txt](https://github.com/travelping/smartcapwap/files/422387/capwap-crash.log.txt)

The certificate I use to connect to the server might be invalid, but never the less the "Assertion failed" should not happen I guess.

**Comment by nm-mrt** [comment]
Looks like I provided the wrong .crt file in application->dtls->x509->calist. Never the less the application should not crash, right?

**Comment by thz** [comment]
If your posted crash-log is indeed smartcapwap's reproducable way to say "i do not trust that AC", then we should add a trust-validation before running into the DTLS code.
